#!/usr/bin/env bash

sudo apt-get install neovim i3 tmux git feh rofi dnust dmenu kitty firefox-esr pipx
if [[ ! -e "$HOME/.vim/autoload/plug.vim" ]]; then
	curl --create-dirs -fLo "$HOME/.vim/autoload/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim  
fi

if [[ ! -e "$HOME/.local/share/nvim/site/autoload/plug.vim" ]]; then
	mkdir -p "$HOME/.local/share/nvim/site/autoload" 
	ln -sf "$HOME/.vim/autoload/plug.vim" "$HOME/.local/share/nvim/site/autoload/plug.vim"
fi

if ! pipx list | grep -q 'pywal'; then
	pipx install 'pywal16'
fi

if [[ ! -v XDG_CONFIG_HOME ]]; then
	XDG_CONFIG_HOME="$HOME/.config"
fi

echo "ln -sf $PWD/configs/polybar/launch $PWD/configs/i3/bin/launchbar"
ln -sf "$PWD/configs/polybar/launch" "$PWD/configs/i3/bin/launchbar"

for f in configs/*; do
	base=$(basename "$f")
	dest="$XDG_CONFIG_HOME/$base"
	if [[ "$base" == "vimrc" ]] || [[ "$base" == "tmux.conf" ]]; then
		echo "ln -sf '$PWD/$f' '$HOME/.$base'"
		ln -sf "$PWD/$f" "$HOME/.$base"
	else
		if [[ -d "$dest" ]]; then
			echo "rm -rf '$dest'"
			rm -rf "$dest"
		fi
		echo "ln -sf '$PWD/$f' '$dest'"
		ln -sf "$PWD/$f" "$dest"
	fi
done
